### PR TITLE
Adding R Language Collective room to Sloshy

### PR DESCRIPTION
**Pull request by MdoubleDash**

### CODE REVIEW

**Comment by MdoubleDash** [comment]
RO approved this;
https://chat.stackoverflow.com/transcript/message/56277450#56277450

**Comment by ndattani** [comment]
I'll point out that this RO is a Community Manager (a type of Stack Exchange employee): https://stackoverflow.com/users/21182738/sasha

**Comment by ndattani** [comment]
Since the changes in this version (#48 https://github.com/tripleee/sloshy/pull/48/files) are identical to the changes in #49 (https://github.com/tripleee/sloshy/pull/49/files), I wonder why deleted the head in #48 and opened a new (identical) pull request #49?

**Comment by tripleee** [comment]
My understanding is that the first PR was redacted because they had not yet received approval from a room owner. For the record, marking the PR as incomplete with a simple comment, and adding the missing information later would probably be smoother. (Github lets you mark a PR as WIP for Work In Progress, but the volume of PRs is obviously low in this project, so we don't strictly need to stick to formalities.)

**Pull request closed without merging**
