### PR TITLE
Add two rooms on the watch list

### PR DESCRIPTION
**Pull request by Oaphi**
This PR humbly makes a request to include two more rooms on the watch list:
- Google Apps Script chat community (of which I am one of the ROs)
- V-eye (personal room for monitoring/managing FAQ proposals)

### CODE REVIEW

**Comment by Oaphi** [comment]
@tripleee thanks for merging! Any help needed with the build issue?

**Comment by tripleee** [comment]
@Oaphi You will need to give Sloshy access to the "V-eye" room before this will work.

**Comment by Oaphi** [comment]
> @Oaphi You will need to give Sloshy access to the "V-eye" room before this will work.

Oh, that's embarrassing, I forgot I've set it up as a gallery room - gave it explicit write access 😅

**Comment by tripleee** [comment]
@Oaphi The V-eye room was (somewhat mysteriously) frozen on December 8th. I will remove it from the configuration file for the time being, but I'll be happy to add it back if it can be revived.

The room had activity on November 30 so it should not have been frozen yet, if my understanding of the logic is correct.

**Comment by tripleee** [comment]
https://chat.stackoverflow.com/faq#retention outlines the criteria for deletion. The room can be deleted if it only contains messages from a single correspondent. I suppose Sloshy could be made responsible for adding another voice; I'm sorry I did not include this in the criterial originally.

**Comment by Oaphi** [comment]
> https://chat.stackoverflow.com/faq#retention outlines the criteria for deletion. The room can be deleted if it only contains messages from a single correspondent. I suppose Sloshy could be made responsible for adding another voice; I'm sorry I did not include this in the criteria originally. 

Hi @tripleee - ah, no worries, that is on me, with my experience I should've noticed this issue coming. I guess the simplest thing is for me to recreate it and ensure it does not fall under deletion criteria next time. Then submit another PR for the room once it is ready to go

**Comment by tripleee** [comment]
Sounds like a plan. I have a feature request which I might well want to implement and test in conjunction with that, but I won't be able to complete it this week.

**Comment by Oaphi** [comment]
@tripleee speaking of the feature request - which one do you refer to? I can either resubmit the new room now (already restored everything I need) or after a specific point later if you'd like it specifically timed. It is not like I am in any rush to keep the rooms unfrozen in the meantime.

**Comment by tripleee** [comment]
Please just go ahead, it will add some incentive for me to finish the code I have in progress. The concrete proposal I have is to add a second test for pull requests which checks that Sloshy has write access and if so posts an announcement to the new room.

**Pull request merged**
