### PR TITLE
Adding R Language Collective chatroom to Sloshy

### PR DESCRIPTION
**Pull request by MdoubleDash**
Approved by the RO: https://chat.stackoverflow.com/transcript/message/56277450

### CODE REVIEW

**Comment by MdoubleDash** [comment]
https://github.com/tripleee/sloshy/pull/48

**Comment by tripleee** [comment]
Thanks for the contribution!

**Comment by tripleee** [comment]
https://chat.stackoverflow.com/transcript/message/56283439#56283439

**Comment by MdoubleDash** [comment]
> Thanks for the contribution!

I wouldn't call that contribution :) Thank you.

**Pull request merged**
