### PR TITLE
Added 24 chat rooms to sloshy.yaml

### PR DESCRIPTION
**Pull request by ndattani**
- 23 from MMSE 
- 1 from Area51

**I assumed the `name` doesn't have to exactly match the chatroom's URL because `name: "sloshy"` doesn't exactly match the chatroom title `Sloshy the Thawman`, but I can certainly change all my `name` fields if necesasry.**

### CODE REVIEW

**Comment by tripleee** [comment]
Thanks for your contribution! I'm hesitant to add this many rooms without an opinion from room owners or site moderators, though. Could you please ask for someone with suitable authority to weigh in on this PR, or perhaps at least document room ownership (I assume most of them are yours?)

**Comment by tripleee** [comment]
Also, as a matter of simple aesthetics, could you trim the empty lines from the end and rebase? Thanks.

**Comment by ndattani** [comment]
I think I'm the room owner of all of the rooms, but let's see if @TyBalduf (a moderator at MMSE) can reply with explicit approval. I'll remove the empty lines from the end though!

**Comment by TyBalduf** [comment]
I'm a [mod](https://mattermodeling.stackexchange.com/users/7/tyberius?tab=profile) for Matter Modeling SE. I'm fine with seeing all these rooms added. We are trying to maintain rooms for specific topics, but because the site is still pretty young, there are times where we have a lack of activity. This will save us the trouble of having to go through and comment or unfreeze them.

**Comment by tripleee** [comment]
Thanks for the fixes. Could you still remove the duplicate noted by @TyBalduf please? Also, a rebase to a single commit (or maybe two commits) would be nice.

**Comment by tripleee** [comment]
Also, for what it's worth, Sloshy does not yet have enough rep on meta, but I'm working furiously on that (-:

**Comment by ndattani** [comment]
I hadn't seen that added point about QChem being listed twice, since that came in an edit to the original comment. @TyBalduf I typically use `edits` to fix typos and such, and write a new comment altogether if adding new information (like tripleee did in the last 2 comments). If there's no new comments since the last visit, a third-party observer won't easily know that something's been added when they re-visit the page.

I've removed the duplication of QChem.

I ran `git rebase -i HEAD~3` and squashed the most recent 3 commits into 1 commit, so the following 3 commits are all [in one](https://github.com/tripleee/sloshy/pull/2/commits/9e03e9f21ef316342e1bdfabe668971603a3de22):

1) removal of whitespace at the end of the file
2) removal of duplicate QChem entry
3) Adding chat.meta.stackexchange.com (I see you gained rep because the edits were approved!)

**Comment by tripleee** [comment]
The rebase seems wrong, it wants to add six commits instead of one?

I didn't have enough rep on meta until this morning but this is now good to go if you can fix the rebase. Alternatively, if you prefer, I can try to finish it up.

**Comment by ndattani** [comment]
About the rebase, I ran the command `git rebase -i HEAD~3` to prepare for the squash of the most recent 3 commits. In the screen that popped up, I replaced `pick` by `s` for the last 2/3 commits, so that they would be "squashed" with the 1st of the 3 commits. This combined 3 commits into one, so I thought that my 4 commits would become just 2 commits. I followed [these instructions](https://www.internalpointers.com/post/squash-commits-into-one-git).

But strangely I couldn't push this without first doing a `merge` (even though I was completely up-to-date with the remote repo, because I had just cloned it before starting to do the rebase/squash). This merge brought my branch up to 5 commits, then the squashed commit which combined 3 commits into 1, was added as an additional commit instead of *replacing* three commits by 1, and this brought me up to 6 commits when I was only expecting it to be 2 in total.

Yes if you're able to finish it up, that would be nice.

**Comment by tripleee** [comment]
I have often found that I need to `git pull --rebase master` after a rebase to realign the commit history. Maybe this should be reported as a bug in Git; I don't know. Anyway, I can take it from here.

**Pull request merged**
