### PR TITLE
Add two more rooms to the watchlist

### PR DESCRIPTION
**Pull request by Oaphi**
This PR adds two more rooms to Sloshy's watchlist:

- V-eye (keeping track of FAQ-proposals) as a follow-up to #18
- ElectionBot development room on the chat.stackexchange.com domain

### CODE REVIEW

**Comment by tripleee** [comment]
Thanks, I will need to perform some updates to this because I have a push forthcoming which necessitates some changes to the YAML schema. But the change is welcome as such; thanks for following up.

**Comment by Oaphi** [comment]
> Thanks, I will need to perform some updates to this because I have a push forthcoming which necessitates some changes to the YAML schema. But the change is welcome as such; thanks for following up.

No worries - just let me know if you will need me to patch up the PR after that, and thanks for making Sloshy - GenericBot is a bit heavy for the task, and making another bot seemed like an unnecessary duplication of effort.

**Comment by tripleee** [comment]
Sorry for the slow progress. I'll merge this one of these days when I have some time to finish the other PR I am working on (#23).

**Comment by Oaphi** [comment]
@tripleee don't worry about it - thanks for keeping me posted, there is no rush to get it merged. 
Let me know if there is anything I can do on my side in the meantime

**Pull request merged**
